### ISSUE TITLE
Attempt to install fails

### ISSUE THREAD

**Issue by noelrappin** [kristianmandrup/ember-easyform-cli#1]
Attempt to install per instructions:

From my `package.json`:

```
"dependencies": {
    "ember-cli-pretender": "^0.3.1",
    "ember-easyform-cli": "git://github.com/kristianmandrup/ember-easyform-cli.git#master"
  }
```

And when running ember server after an `npm install`:

```
Path or pattern "distributions/ember-easyform-cli.js" did not match any files [string exception]
Error: Path or pattern "distributions/ember-easyform-cli.js" did not match any files [string exception]
    at /usr/local/lib/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:34:15
    at $$$internal$$tryCatch (/usr/local/lib/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
```

I'm not super npm savvy, so it's possible I missed something

**Comment by kristianmandrup** [comment]
Yes, unfortunately it is not working just yet. But most of the infratructure is in place. Was a learning process. You are welcome to try and fix it.

Ember CLI currently requires either AMD modules or that everything is packed as a "global" via f.ex Browserify and included as a bower component via Brocfile or similar.

Start with this article, best I found so far...

http://blogs.telerik.com/kendoui/posts/13-05-08/requirejs-fundamentals

Been investigating a lot about all this lately... see my blog posts here

http://infomatrix-blog.herokuapp.com/tag/cli

Hope that gives you an overview and enough knowledge to proceed and make it work ;)

We have some CLI discussions here on how to make all this much easier in the near future :)

https://github.com/stefanpenner/ember-cli/issues/2120

**Comment by kristianmandrup** [comment]
I believe  one way would be to use a shim like this:

http://requirejs.org/docs/api.html#config-shim

I believe that the baseUrl is the project root, as per the Brocfile

http://requirejs.org/docs/api.html#config-baseUrl

or perhaps sth like this?

https://github.com/cujojs/curl

Just some food for thought...

**Comment by kristianmandrup** [comment]
Basically, it is as simply as this. Make `ember-easyform-cli.js` available under your `bower_components` or `vendor` dir. Then load it via a `<script>` tag from `index.html`. When that works, see if you can reference it via an `app.import(' ...');` in your `Brocfile.js`. Afte that, see if you can achieve the same by doing the same `app.import(' ...');` in the addon `index.js` entry point file in the  `included:` hook.

For an example, see the [ember-cli-bootstrap](https://github.com/dockyard/ember-cli-bootstrap/blob/master/index.js) curiously also by Dockyard.

What we need is one repo, which exposes the library as a bower component, then test that works on its own, then a thin ember-cli addon wrapper. This is how all the existing addons are currently designed.

**Comment by kristianmandrup** [comment]
I made this little experiment

``` javascript
// bower_components/ember-validations/index.js
Ember.Validations = Ember.Namespace.create({
    VERSION: '1.0.0',
    name: 'validations'
});

console.log('hello from Ember.Validations', Ember.Validations);
```

``` javascript
// Brocfile.js
app.import(app.bowerDirectory + '/ember-validations/index.js');

module.exports = app.toTree();
```

`ember serve`

and voila :)

**Comment by kristianmandrup** [comment]
After some effort I finally got both Ember.EasyForms and Ember.Validations working :)

``` json
// bower.json

    "ember-validations": "kristianmandrup/ember-validations#master",
    "ember-easyform": "kristianmandrup/ember-easyForm#master",
```

And 

``` json
// package.json

    "ember-validations-cli": "git://github.com/kristianmandrup/ember-validations-cli.git#master",
    "ember-easyform-cli": "kristianmandrup/ember-easyform-cli#master",
```

Enjoy ;)
